# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'docker-service-connection'
  imageRepository: 'pdesaidocker/easy-kart-api-reviews'
  containerRegistry: 'pdesaidocker'
  tag: '$(Build.BuildId)'
  System.Debug: true

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: BuildAndPush
      displayName: Build and Push Docker Image
      steps:    
      - task: DotNetCoreCLI@2
        inputs:
           command: 'restore'
           projects: 'EasyKart.Reviews/EasyKart.Reviews.csproj'         
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'EasyKart.Reviews/EasyKart.Reviews.csproj'
          arguments: '--configuration Release'
      - task: Docker@2
        displayName: Build and push Docker image
        inputs:
          command: 'buildAndPush'
          repository: $(imageRepository)
          dockerfile: 'EasyKart.Reviews/Dockerfile'
          buildContext: '.'
          tags: $(tag)
          containerRegistry: $(dockerRegistryServiceConnection)
